Add APIs required for the CalDAV trashbin
nextcloud/cdav-library pull request #474
Opened 2021-05-28 12:39 UTC by ChristophWurst

Required for https://github.com/nextcloud/calendar/pull/3118

* Expose new property specific to deleted calendars
* API to MOVE calendars (or anything else) from one location to another

2021-05-28 13:23 UTC, tcitworld requested changes

2021-05-28 13:23 UTC, tcitworld commented on src/parser.js
> +		this.registerParser('{http://nextcloud.com/ns}deleted-at', Parser.decInt);
Add a new date parser instead of just returning an int.

Also it makes me think a timestamp isn't necessarily the best format.

2021-05-28 13:27 UTC, ChristophWurst commented on src/parser.js
> +		this.registerParser('{http://nextcloud.com/ns}deleted-at', Parser.decInt);
what other format should we use? we use timestamps quite consistently across nextcloud

2021-05-28 13:39 UTC, tcitworld commented on src/parser.js
> +		this.registerParser('{http://nextcloud.com/ns}deleted-at', Parser.decInt);
It would be nice to be readable straight away, so I'd say ISO8601?

2021-05-28 13:55 UTC, ChristophWurst commented on src/parser.js
> +		this.registerParser('{http://nextcloud.com/ns}deleted-at', Parser.decInt);
Fair enough. I'll see what I can do once the basic functionality is there.

2021-05-31 18:37 UTC, ChristophWurst commented on src/parser.js
> +		this.registerParser('{http://nextcloud.com/ns}deleted-at', Parser.decInt);
I will schedule a refactoring after the basics are done. This change also requires a touch of the server part, obviously ;)

2021-05-31 18:47 UTC, GretaD approved these changes

2021-05-31 18:48 UTC, merged